[package]
name = "stark-anatomy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = { version = "0.10", default-features = false }
blake2 = "0.10.4"